[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "regular"

[window]
dynamic_padding = true
opacity = 0.85

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
